### ISSUE TITLE
Incorrect `rrule` for `conv`?

### ISSUE THREAD

**Issue by trahflow** [bionanoimaging/FourierTools.jl#35]
Hi,

I was wondering whether the `ChainRules.Core.rrule` for `conv` [defined here](https://github.com/bionanoimaging/FourierTools.jl/blob/8fbc1cafb2e19c4687154490b5bb93c21cbbf56b/src/convolutions.jl#L79-L87) is actually correct?

The following test against finite differencing `using ChainRulesTestUtils` gives large errors:
```julia
x = randn(ComplexF64, (5,6))
y = randn(ComplexF64, (5,6))
test_rrule(
    Zygote.ZygoteRuleConfig(),
    conv,
    x,
    y;
    rrule_f=Zygote.rrule_via_ad
)
```

Of course finite differencing is not the gold standard, but if I delete the custom `rrule`, Zygote uses the `rrule`s for `fft` and `ifft` ([as defined in AbstractFFTs.jl](https://github.com/JuliaMath/AbstractFFTs.jl/blob/79789f2250aed0d70d2e1766667cc4dde7b43896/ext/AbstractFFTsChainRulesCoreExt.jl)) and that test passes just fine.

What is the motivation for a custom rule here anyway? Note that just using AbstractFFTs would give you also thunking/unthunking, correct `ProjectTo`s and also tangents for the second argument.

**Comment by roflmaostc** [comment]
Hi!

You're right. The reason back then was performance. Zygote does not support thunk/unthunk.

But I'm using thst definition nowhere, so we should fix it.
