### ISSUE TITLE
Missing tests for czt

### ISSUE THREAD

**Issue by roflmaostc** [bionanoimaging/FourierTools.jl#9]
CC @RainerHeintzmann

**Comment by RainerHeintzmann** [comment]
Well, the docstrings are there but not integrated via `Documenter`. Will do this and write some tests.

**Comment by roflmaostc** [comment]
@RainerHeintzmann two lines are still missing
https://codecov.io/gh/bionanoimaging/FourierTools.jl/src/main/src/czt.jl#
